kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo
  labels:
    name: mongo-deployment
    app: demo
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    matchLabels:
     name: mongo
     role: mongodb
     app: demo
  template:
    spec:
      containers:
        - name: mongo
          image: mongo:4.0
          ports:
            - containerPort: 27017
              name: mongo
          command: ["mongod", "--smallfiles", "--bind_ip", "0.0.0.0"]
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: mongo
        role: mongodb
        app: demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
    app: demo
    role: mongodb
