apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-playground
  labels:
    app: security-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-playground
  template:
    metadata:
      labels:
        app: security-playground
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
      containers:
      - name: security-playground
        image: ghcr.io/mikescholl-sysdig/security-playground:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: security-playground-aws-credentials
        resources:
          limits:
            cpu: 2000m
            memory: 3000Mi
          requests:
            cpu: 100m
            memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: security-playground
  name: security-playground
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
  selector:
    app: security-playground
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: security-playground
  name: security-playground-aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: REPLACE_ACCESS
  AWS_SECRET_ACCESS_KEY: REPLACE_SECRET
  AWS_DEFAULT_REGION: REPLACE_REGION