apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "monitor-event-trigger.fullname" . }}
  labels:
{{ include "monitor-event-trigger.labels" . | indent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "monitor-event-trigger.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          serviceAccountName: {{ include "monitor-event-trigger.fullname" . }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - -X
                - POST
                - -s
                - '{{ .Values.prefixUrl }}/api/events'
                - -H
                - 'Content-Type: application/json; charset=UTF-8'
                - -H
                - 'Accept: application/json, text/javascript, */*; q=0.01'
                - -H
                - "Authorization: Bearer $(SDC_ACCESS_TOKEN)"
                - --data-binary
                - '{{ .Values.eventPayload }}'
              env:
                - name: SDC_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "monitor-event-trigger.fullname" . }}-apitoken
                      key: apitoken
          restartPolicy: {{ .Values.restartPolicy }}
