apiVersion: v1
kind: Pod
metadata:
  name: loadgen-cpu
  namespace: stress-test-cpu
spec:
  containers:
    - name: memory-demo-2-ctr
      image: polinux/stress
      resources:
        requests:
          cpu: "500m"
        limits:
          cpu: "1000m"
      command: ["stress"]
      args: ["--cpu", "8"]
