apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database-container
        image: postgres:latest
        env:
        - name: POSTGRES_PASSWORD
          value:
