apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: nginx:1.21.1
        lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
