apiVersion: v1
kind: Service
metadata:
  name: javasimpleserver
  namespace: javaserver
spec:
  selector:
    app: javasimpleserver
  ports:
  - name: app-port
    protocol: TCP
    port: 8030
    targetPort: 8030
  - name: metrics-port
    protocol: TCP
    port: 9090
    targetPort: 9090
  type: LoadBalancer

