apiVersion: v1
kind: Pod
metadata:
  name: loadgen
  namespace: stress-test
spec:
  containers:
    - name: memory-demo-2-ctr
      image: polinux/stress
      resources:
        requests:
          memory: "50Mi"
        limits:
          memory: "100Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "120M", "--vm-hang", "1"]
