apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver-container
        image: ngin:latest
