kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    name: nginx-deployment
    app: web-app
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
     name: nginx
     role: nginx
     app: web-app
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.15.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.1
              memory: 128Mi
            requests:
              memory: 64Mi
              cpu: 0.05
    metadata:
      labels:
        name: nginx
        role: nginx
        app: web-app
