kind: Deployment
apiVersion: apps/v1
metadata:
  name: python
  labels:
    name: python-deployment
    app: python-app
  namespace: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
     name: python-app
     role: python-app
     app: python-app
  template:
    spec:
      containers:
        - name: python-app
          image: learnsysdig/python-app:0.1.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.1
              memory: 128Mi
            requests:
              memory: 64Mi
              cpu: 0.05
    metadata:
      labels:
        name: python-app
        role: python-app
        app: python-app
