apiVersion: v1
data:
  dragent.yaml: |
    configmap: true
    ### Agent tags
    # tags: linux:ubuntu,dept:dev,local:nyc

    #### Sysdig Software related config ####

    # Sysdig collector address
    # collector: 192.168.1.1

    # Collector TCP port
    # collector_port: 6666

    # Whether collector accepts ssl
    # ssl: true

    # collector certificate validation
    # ssl_verify_certificate: true

    #######################################
    # new_k8s: true
    # k8s_cluster_name: production
    k8s_cluster_name: instruqt-training
    collector: ingest-eu1.app.sysdig.com
    collector_port: 6443
    ssl: true
    ssl_verify_certificate: true
    new_k8s: true
    use_promscrape: true
    prometheus:
      enabled: true
      interval: 10
      ingest_raw: true
      ingest_calculated: false
      log_errors: true
      max_metrics: 10000
      max_metrics_per_process: 20000
kind: ConfigMap
metadata:
  name: sysdig-agent
  namespace: sysdig-agent
