version: "3"

services:
    node-exporter:
        container_name: node_exporter
        image: quay.io/prometheus/node-exporter
        network_mode: host
        pid: host
        volumes:
            - "/:/host:ro,rslave"
        environment:
            - "--path.rootfs=/host"
        ports:
            - "9100:9100"
        labels:
            - "io.prometheus.scrape=true"    
            - "io.prometheus.port=9100"
