apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-workload
  labels:
    app: prom-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-workload
  template:
    metadata:
      labels:
        app: prom-workload
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
      containers:
      - name: prom-workload
        image: placeholder
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prom-workload-end
  name: prom-workload-svc
spec:
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: prom-workload
  type: NodePort
