apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: database-monitor-daemon
  namespace: distributed-db
spec:
  selector:
    matchLabels:
      app: db-monitor
  template:
    metadata:
      labels:
        app: db-monitor
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - distributed-db
              topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: db-monitor-agent
        image: prom/node-exporter:v1.2.2
        ports:
        - containerPort: 9100
          protocol: TCP
