pipeline {
    agent {
       kubernetes {
           yaml """
apiVersion: v1
kind: Pod
metadata:
    name: dind
    annotations:
      container.apparmor.security.beta.kubernetes.io/dind: unconfined
      container.seccomp.security.alpha.kubernetes.io/dind: unconfined
spec:
    containers:
      - name: dind
        image: docker:dind
        securityContext:
          privileged: true
        tty: true
        volumeMounts:
        - name: var-run
          mountPath: /var/run
      - name: jnlp
        securityContext:
          runAsUser: 0
          fsGroup: 0
        volumeMounts:
        - name: var-run
          mountPath: /var/run

    volumes:
    - emptyDir: {}
      name: var-run
"""
       }
   }

    stages {
        stage('Build Image') {
            steps {
                container("dind") {
                    sh "docker pull sysdiglabs/dummy-vuln-app"
                    sh "echo sysdiglabs/dummy-vuln-app > sysdig_secure_images"
                }
            }
        }
        stage('Scanning Image') {
            steps {
                // This will always be executed in the JNLP container
                sysdig engineCredentialsId: 'sysdig-secure-api-credentials', engineurl: 'https://secure.sysdig.com', name: 'sysdig_secure_images', inlineScanning: true
            }
        }
   }
}
