version: "3"

services:
    nginx:
        container_name: nginx-server
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./index.html:/usr/share/nginx/html/index.html
            - ./nginx.conf:/etc/nginx/nginx.conf     
    nginx-exporter:
        container_name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.5.0
        restart: always
        command: -nginx.scrape-uri http://nginx:80/metrics -nginx.retries 50 -nginx.retry-interval 10s
        ports:
            - "9113:9113"
        labels:
            - "io.prometheus.scrape=true"
            - "io.prometheus.port=9113"
