apiVersion: apps/v1
kind: Deployment
metadata:
  name: sko-2026-deployment-with-root-group-1
  namespace: group-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example-container
          image: nginx:latest
          securityContext:
            runAsUser: 0