{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "license-manager:ListDistributedGrants",
                "license-manager:ListLicenseConfigurations",
                "fms:ListPolicies",
                "license-manager:ListReceivedLicenses",
                "license-manager:GetServiceSettings",
                "fms:ListMemberAccounts",
                "ec2:DescribeInternetGateways",
                "gamelift:DescribeFleetCapacity",
                "ec2:CreateCarrierGateway",
                "organizations:DescribeOrganization",
                "fms:GetNotificationChannel",
                "ec2:CreateInternetGateway",
                "gamelift:ListBuilds",
                "iam:GetAccountAuthorizationDetails",
                "ec2:DescribeNetworkAcls",
                "ec2:DescribeRouteTables",
                "license-manager:ListReceivedGrants",
                "servicequotas:ListServiceQuotas",
                "iam:ListPolicies",
                "ec2:DescribeLaunchTemplates",
                "ec2:CreateTags",
                "fms:ListAdminAccountsForOrganization",
                "ec2:CreateCustomerGateway",
                "license-manager:ListResourceInventory",
                "license-manager:ListLicenseConversionTasks",
                "license-manager:ListLicenses",
                "license-manager:ListTokens",
                "ec2:DescribeVpcEndpoints",
                "ec2:DescribeVpnGateways",
                "iam:GetAccountSummary",
                "servicequotas:ListServices",
                "ec2:CreateNatGateway",
                "ec2:CreateVpc",
                "servicequotas:GetServiceQuota",
                "license-manager:ListLicenseSpecificationsForResource",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DescribeAvailabilityZones",
                "ec2:DescribeCarrierGateways",
                "fms:GetAdminScope",
                "ec2:AttachVpnGateway",
                "iam:ListRoles",
                "ec2:DescribeNatGateways",
                "ec2:DescribeCustomerGateways",
                "ec2:DescribeLocalGateways",
                "license-manager:ListReceivedLicensesForOrganization",
                "fms:GetAdminAccount",
                "ec2:DescribeVpcs",
                "iam:ListUsers",
                "iam:ListGroups",
                "license-manager:ListReceivedGrantsForOrganization",
                "s3:GetObject",
                "s3:ListAllMyBuckets",
                "s3:ListBucket"
            ],
            "Resource": "*"
        }
    ]
}