apiVersion: v1
kind: ConfigMap
metadata:
  name: example-voting-app
  labels:
    name: example-voting-app
    app: example-voting-app
  namespace: lab2-example-voting-app
data:
  redis_host: 'redis'
