apiVersion: v1
kind: Secret
metadata:
  name: example-voting-app
  labels:
    name: example-voting-app
    app: example-voting-app
  namespace: lab2-example-voting-app
type: Opaque
data:
  db_url: 'cG9zdGdyZXM6Ly9wb3N0Z3Jlc0BkYi9wb3N0Z3Jlcw=='
  redis_url: 'cmVkaXM6Ly9yZWRpcy8w'
  jdbc_db_url: 'amRiYzpwb3N0Z3Jlc3FsOi8vZGIvcG9zdGdyZXM='
