kind: Deployment
apiVersion: apps/v1
metadata:
  name: vote
  labels:
    name: vote-deployment
    app: example-voting-app
  namespace: lab2-example-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
     name: vote
     role: voteapp
     app: example-voting-app
  template:
    spec:
      containers:
        - name: vote
          image: nestorsalceda/example-voting-app-vote
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: example-voting-app
                  key: redis_url
          resources:
            limits:
              cpu: 0.25
              memory: 128Mi
            requests:
              memory: 64Mi
    metadata:
      labels:
        name: vote
        role: voteapp
        app: example-voting-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: vote
  name: vote
  namespace: lab2-example-voting-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: vote
    app: example-voting-app
    role: voteapp
