kind: Deployment
apiVersion: apps/v1
metadata:
  name: voter
  labels:
    name: voter-deployment
    app: example-voting-app
  namespace: lab2-example-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
     name: voter
     role: voterapp
     app: example-voting-app
  template:
    spec:
      containers:
        - name: voter
          image: bencer/example-voting-app-voter:0.1
          env:
            - name: VOTE
              value: "vote.lab2-example-voting-app.svc.cluster.local"
            - name: PORT
              value: "80"
          resources:
            limits:
              memory: 64Mi
            requests:
              memory: 32Mi
    metadata:
      labels:
        name: voter
        role: voterapp
        app: example-voting-app
