#!/bin/bash

set -xe

git clone https://github.com/draios/instruqt-assets/ /tmp/instruqt-assets
cp /tmp/instruqt-assets/oss/sysdig-intro/simulate-load /usr/local/bin/
chmod +x /usr/local/bin/simulate-load

# echo "alias curl=\"curl -s -o /dev/null\"" >> ~/.bashrc

apt-get purge nginx -y && apt-get autoremove -y
apt-get update

docker pull wordpress:php8.1-apache
docker pull wordpress:cli
docker pull mysql:5.7
docker pull jwilder/nginx-proxy:alpine

docker-compose up -d

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  sleep 1
done

(docker run \
    --name mysql \
    -v /data:/var/lib/mysql \
    -e MYSQL_ROOT_PASSWORD='toor' \
    -d mysql

docker run \
    --name wp \
    -e WORDPRESS_DB_USER=root \
    -e WORDPRESS_DB_PASSWORD=toor \
    -e VIRTUAL_HOST=wp \
    --link mysql:mysql \
    -d wordpress

docker run 
    --name proxy \
    -p 80:80 \
    -e DEFAULT_HOST=wp \
    -v /var/run/docker.sock:/tmp/docker.sock:ro -d jwilder/nginx-proxy:alpine)

docker run -it --rm \
        --volumes-from wp \
        --network container:wp \
        -e WORDPRESS_DB_USER=wordpress \
        -e WORDPRESS_DB_PASSWORD=wordpress \
        wordpress:cli post create --post_type=page --post_status=publish --post_author=sysdig-user --post_title="Post $RANDOM" 


        curl --data-urlencode "weblog_title=MY_BLOG_NAME" \
     --data-urlencode "user_name=MYUSERNAME" \
     --data-urlencode "admin_password=MYPASSWORD" \
     --data-urlencode "admin_password2=MYPASSWORD" \
     --data-urlencode "admin_email=MY@EMAIL.COM" \
     --data-urlencode "Submit=Install+WordPress" \
     http://wordpress_host/path_if_any/wp-admin/install.php?step=2


    #  docker exec wpcli wp post create --post_type=page --post_status=publish --post_author=sysdig-user --post_title="Post $RANDOM" 
# https://stackoverflow.com/questions/10062513/install-wordpress-using-bash-shell-without-visiting-wp-admin-install-php
docker exec wpcli wp core install --url=localhost --title=sysdig-training --admin_email=pjlz@email.com --admin_password=password --admin_user=sysdig

docker exec wpcli wp theme install twentysixteen --activate
docker exec wpcli wp theme install hestia --activate