#docker run -p 2121:21 -p 30000-30009:30000-30009 -it --rm --name=proftpd-bleed kacperzuk/heartbleed-testbed-proftpd-bleed
apiVersion: v1
kind: Pod
metadata:
  name: proftpd-bleed
  labels:
    purpose: heartbleed-testbed
spec:
  containers:
  - name: proftpd-bleed
    image: kacperzuk/heartbleed-testbed-proftpd-bleed
    ports:
     - "2121:21"
     - "30000-30009:30000-30009"
