sysdig: 
  settings: 
    feature:  
      mode: troubleshooting
    new_k8s: true
    snaplen: 512
    autodrop:
      enabled: true
      upper_threshold: 80      
    app_checks:
      - name: ntp
        check_module: ntp
        pattern:
          comm: ntpd
    percentiles: [50, 95, 99]
    tags: role:cluster