apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: cassandra
  name: cassandra
spec: 
  ports:
    - port: 9042
      targetPort: cassandra
  selector:
    name: cassandra 
    app: demo
    role: cassandradb
