apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: javaapp
  name: javaapp
spec: 
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: javaapp 
    app: demo
    role: jfrontend
