kind: Deployment
apiVersion: apps/v1
metadata:
  name: jclient
  labels:
    name: jclient-deployment
    app: demo
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    matchLabels:
     name: client
     role: jclients
     app: demo
  template:
    spec:
      containers:
        - name: client
          image: ltagliamonte/recurling
          env:
          - name: URL
            value: http://javaapp.java-app.svc.cluster.local:8080/simpleWebJava/TestServlet
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: client
        role: jclients
        app: demo
