apiVersion: v1
kind: Service
metadata:
  name: sko-2025-service-{{ group_id }}
  namespace: {{ group_id }}
spec:
  selector:
    app: main
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer