apiVersion: apps/v1
kind: Deployment
metadata:
  name: zodiac
  labels:
    app: zodiac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zodiac
  template:
    metadata:
      labels:
        app: zodiac
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
      containers:
      - name: zodiac
        image: placeholder
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zodiac-end
  name: zodiac-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: zodiac
  type: NodePort