apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-requester-deployment
  namespace: javaserver
  labels:
    app: simple-requester
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-requester
  template:
    metadata:
      labels:
        app: simple-requester
    spec:
      containers:
      - name: simple-requester
        image: mateobur/simple-requester:0.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

